### ISSUE TITLE
Wrong extraction of SVG dimensions

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#17]
If the SVG data contains a `<rect>` element with `width` and `height` attributes, these values will be wrongly used as the width and height of the whole SVG, due to `extractWidth()` and `extractHeight()` running the following regular expressions on the full data, instead of just the top-level SVG node:

```js
function extractWidth(data) {
    const matches = data.match(/width=(["'])([^%]+?)\1/i);

    if (matches) return parseDimension(matches[2]);
}

function extractHeight(data) {
    const matches = data.match(/height=(["'])([^%]+?)\1/i);

    if (matches) return parseDimension(matches[2]);
}
```

Attached an example of an SVG where the wrong dimensions are extracted.

[test-1.svg](https://github.com/SidOfc/leather/assets/213275/c40dcd85-1b83-49b9-a81f-566aaaaf4c15)

**Comment by lehni** [comment]
The content is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 640 480">
  <rect x="100" y="100" width="64" height="48"/>
</svg>
```

And instead of the expected  `{ width: 640, height: 480 }`, leather returns `{ width: 64, height: 48 }` from the `<rect>` element.

**Comment by SidOfc** [comment]
Hello there! Cheers for writing up #18, I also went at it myself and only found your PR afterwards. Your fix is better though as it stops looping through the file as soon as the closing SVG tag bracket is found which also reduces the chance for other `width` / `height` properties being captured.

Thank you very much for reporting the issue and providing a patch! Have a good one!
