### ISSUE TITLE
Version needs bumping

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#19]
package.json still shows 2.1.5, while NPM has a 3.0.0 release

**Comment by SidOfc** [comment]
Not sure how this is possible, NPM itself shows the correct version.

<img width="483" alt="image" src="https://github.com/SidOfc/leather/assets/3225058/d7f5a966-464a-4c99-b4b6-1ea4f497f50d">

I also tried installing `leather@3.0.0` in a new npm package and inspecting `node_modules/leather/package.json` also yielded the correct version.

Don't think this is an issue with leather but rather some local package management issue.

Cheers for the report though, additionally 3.0.1 is released so a bump did happen anyways :)

**Comment by lehni** [comment]
Thank you @SidOfc !
