### ISSUE TITLE
Receiving floating point dimension values in some videos

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#24]
While in SVGs, the dimensions appear to be rounded, I am getting strange floating point values for some videos, e.g.:

https://github.com/SidOfc/leather/assets/213275/9a2cb519-8aca-47de-9281-dac297c58e62

**Comment by SidOfc** [comment]
Seems like this is some edge case due to some division. Patched it with a `Math.floor` for both width and height so it should now return integer values for included video. Will mark this as resolved but feel free to reopen if there are other files experiencing the same issue.

Cheers!
